### ISSUE TITLE
Attempting to include --notes on multiple lines with '\n' is reflected incorrectly in the html report

### ISSUE THREAD

**Issue by onlyadam** [wearefriday/gherkin-test-report#20]
Attempting to pass a string containing line breaks (using `\n`) in the `--notes` argument is accepted but when viewing the html report they are shown as `<BR>`.

Example argument:
`npx pumpkin --features features/ --cucumberjson results/report.json --notes 'env: test\n ver: 3.2\n browser: chrome\n os: mac' --open`

Text produced when viewing the html report in chrome:
`env: test<br>ver: 3.2<br>browser: chrome<br>os: mac`

Is this a bug or is there an expected way to pass a string to be displayed on multiple lines as part of the `--notes` argument?
This is what i'm trying to achieve:
<img width="354" alt="Screenshot 2021-10-06 at 13 30 21" src="https://user-images.githubusercontent.com/52462374/136202803-548a87d1-cf5f-4373-9002-348eaa96c633.png">

Also worth mentioning: 
Attempting to pass a list like so:
`--notes '- env: test - ver: 3.2 - browser: chrome - os: mac`
Throws the following error:
`NOTES.split is not a function`

**Comment by nickdunn** [comment]
Fixed in master. 

A couple of things here:

* Pumpkin wasn't converting line breaks correctly, it now will
* In order for these to be _printed_ correctly, Pumpkin runs the notes field through a Markdown parser. The CommonMark (https://commonmark.org/) spec requires that a line _ends_ in two spaces in order for a `<br>` to be inserted. So your example should look like:

```
--notes 'env: test  \nver: 3.2  \nbrowser: chrome  \nos: mac'
```

**Comment by nickdunn** [comment]
Fixed in https://www.npmjs.com/package/@padigital/pumpkin/v/2.0.5
